### ISSUE TITLE
Input variables

### ISSUE THREAD

**Issue by chenyaoy** [xychang/RecursiveHierarchicalClustering#1]
In the input, why does it take in frequency of actions? Doesn't the 2016 paper use time gaps between the actions?

**Comment by xychang** [comment]
By frequency, we actually mean the number of times an action happened.
This version of the code does not include handling of time gap information because it is intended broader applications.
If you want to include time gap information, you can follow similar approach as in the 2016 paper, where we bucketized the time gap, and use "action-gap-action" n-grams as features instead of single actions.
