### ISSUE TITLE
Utilizing multiple servers

### ISSUE THREAD

**Issue by Symash** [xychang/RecursiveHierarchicalClustering#14]
Hi,

I'm running your project with 10000 users with 2 servers using shared storage.
I've set threadNum as 5 and minPerSlice as 1000.

However, when I look into servers status by 'hotp' command, I've found that the project doesn't utilize both of the servers at the same time, but switches the server usage back and forth.

Is this the correct way that you've intended or did I set the parameter (threadNum and minPerSlice) in a wrong way?

In addition, I want to know if there are any guidelines on how to set threadNum and minPerSlice to effectively utilize many servers.

Thanks for your help in advance!

**Comment by xychang** [comment]
Hi,

For your first question, no, the servers should be used at the same time for costly computations.

MinPerSlice is used in the cases where local computation is fast enough (e.g., below 1000 users), so that there is no need of parallel computation. Just set it to a number that your server can handle easily using a single thread.

threadNum is the maximum number of threads to be started on each server. For that I recommend you figure out how many CPU cores do you have on your server and then set it to a number slightly below that.

Note that, the code involves two phases, the distance computation phase and the clustering phase. Parallelism is involved only in distance computation phase, which is probably why you see the server usage changes overtime.

Hope this answers your questions.

**Comment by Symash** [comment]
Thanks for your explanation!

For others, I've found out that it runs the first batch in the first server and then starts running in the other servers.
However, it was that the number of sequences was too big (700K) that the first batch didn't end and it seemed like it keeps running in the first server.

Anyway, thanks for your great project and explanation on setting the variables!
